"""Shared frontend-agnostic canonical UI state.

The ui_state package normalizes authoritative daemon/IPC snapshots into typed,
immutable state objects that multiple frontends can consume.
"""
from __future__ import annotations


from styrened.ui_state.base import (
    CapabilityState,
    DataIssue,
    FieldAuthority,
    KnowledgeState,
    LoadState,
    RefreshMeta,
)
from styrened.ui_state.comms import (
    CommsCapability,
    CommsMode,
    CommsWorkspaceInputs,
    CommsWorkspaceState,
    build_comms_workspace_state,
)
from styrened.ui_state.config import (
    ConfigDraftInputs,
    ConfigDraftState,
    ConfigSaveState,
    ConfigValidationIssue,
    build_config_draft_state,
)
from styrened.ui_state.daemon import (
    LocalDaemonInputs,
    LocalDaemonState,
    OverlayRuntimeState,
    build_local_daemon_state,
)
from styrened.ui_state.mail import (
    ConversationScopeKind,
    DeliveryPathClass,
    ForumThreadMeta,
    GroupParticipantRecord,
    GroupThreadFeatureTier,
    GroupThreadMeta,
    GroupThreadPolicy,
    MailIndexInputs,
    MailIndexState,
    MailMessageRecord,
    MailThreadRecord,
    MailTransportMeta,
    MediaFrictionLevel,
    build_mail_index,
)
from styrened.ui_state.nodes import (
    NodeAuthorityState,
    NodeCatalogInputs,
    NodeCatalogState,
    NodeRecord,
    OverlayAddressState,
    PeerRelationshipState,
    PresenceState,
    RouteAspect,
    RouteKind,
    build_node_catalog,
    build_node_record,
    classify_presence,
)
from styrened.ui_state.page_browser import (
    PageActionCapabilities,
    PageBrowserSessionInputs,
    PageBrowserSessionState,
    PageTransport,
    build_page_browser_session_state,
)
from styrened.ui_state.sessions import (
    SessionIndexInputs,
    SessionIndexState,
    SessionKind,
    SessionRecord,
    SessionStatus,
    build_session_index,
)
from styrened.ui_state.workspace import (
    PeerWorkspaceContext,
    PeerWorkspaceFocus,
    WorkspaceId,
    build_peer_workspace_context,
)

__all__ = [
    "CapabilityState",
    "CommsCapability",
    "CommsMode",
    "CommsWorkspaceInputs",
    "CommsWorkspaceState",
    "ConfigDraftInputs",
    "ConfigDraftState",
    "ConfigSaveState",
    "ConfigValidationIssue",
    "ConversationScopeKind",
    "DataIssue",
    "DeliveryPathClass",
    "FieldAuthority",
    "ForumThreadMeta",
    "GroupParticipantRecord",
    "GroupThreadFeatureTier",
    "GroupThreadMeta",
    "GroupThreadPolicy",
    "KnowledgeState",
    "LoadState",
    "LocalDaemonInputs",
    "LocalDaemonState",
    "MailIndexInputs",
    "MailIndexState",
    "MailMessageRecord",
    "MailThreadRecord",
    "MailTransportMeta",
    "MediaFrictionLevel",
    "NodeAuthorityState",
    "NodeCatalogInputs",
    "NodeCatalogState",
    "NodeRecord",
    "OverlayAddressState",
    "OverlayRuntimeState",
    "PageActionCapabilities",
    "PageBrowserSessionInputs",
    "PageBrowserSessionState",
    "PageTransport",
    "PeerRelationshipState",
    "PresenceState",
    "RefreshMeta",
    "RouteAspect",
    "RouteKind",
    "SessionIndexInputs",
    "SessionIndexState",
    "SessionKind",
    "SessionRecord",
    "SessionStatus",
    "PeerWorkspaceContext",
    "PeerWorkspaceFocus",
    "WorkspaceId",
    "build_comms_workspace_state",
    "build_config_draft_state",
    "build_local_daemon_state",
    "build_mail_index",
    "build_node_catalog",
    "build_node_record",
    "build_page_browser_session_state",
    "build_peer_workspace_context",
    "build_session_index",
    "classify_presence",
]
