"""Cross-language wire protocol compatibility tests — Python side.

Validates that Python IPC protocol encodes frames that match the golden
test vectors consumed by Rust (styrene-ipc-server wire_compat tests).

These tests run standalone (no daemon needed) and verify:
1. Python encode_frame produces the exact bytes in *.bin fixtures
2. Python decode_frame roundtrips through the vectors
3. All fixture vectors have valid IPCMessageType values

The test vectors are generated by generate_vectors.py and live in
the styrene-rs repo at tests/fixtures/ipc-wire/.
"""
import json
import os
import struct
from pathlib import Path

import msgpack
import pytest

from styrened.ipc.protocol import (
    IPCMessageType,
    decode_frame,
    encode_frame,
)

# Path to golden test vectors
FIXTURES_DIR = Path(os.path.expanduser(
    "~/workspace/styrene-lab/styrene-rs/tests/fixtures/ipc-wire"
))

# Fixed request_id used by the generator
FIXED_REQUEST_ID = bytes(range(16))


def get_vector_names():
    """List all test vector names (without extension)."""
    if not FIXTURES_DIR.exists():
        pytest.skip("test vectors not found — run generate_vectors.py first")
    names = set()
    for f in FIXTURES_DIR.iterdir():
        if f.suffix == ".bin":
            names.add(f.stem)
    return sorted(names)


@pytest.fixture(params=get_vector_names() if FIXTURES_DIR.exists() else [])
def vector(request):
    """Load a test vector (bin + json sidecar)."""
    name = request.param
    bin_path = FIXTURES_DIR / f"{name}.bin"
    json_path = FIXTURES_DIR / f"{name}.json"

    bin_data = bin_path.read_bytes()
    meta = json.loads(json_path.read_text())

    return name, bin_data, meta


def test_vector_decode_roundtrip(vector):
    """Python decode_frame decodes the vector, and re-encoding produces
    semantically identical content (same type, request_id, payload values)."""
    name, bin_data, meta = vector

    # Decode
    msg_type, req_id, payload = decode_frame(bin_data)

    # Verify type byte
    expected_type = meta["msg_type_byte"]
    assert f"0x{msg_type:02x}" == expected_type, (
        f"{name}: type mismatch, expected {expected_type}"
    )

    # Verify request ID
    assert req_id == FIXED_REQUEST_ID, f"{name}: request_id mismatch"

    # Re-encode and decode again — roundtrip
    reencoded = encode_frame(IPCMessageType(msg_type), req_id, payload)
    rt_type, rt_id, rt_payload = decode_frame(reencoded)
    assert rt_type == msg_type
    assert rt_id == req_id
    assert rt_payload == payload, f"{name}: payload roundtrip mismatch"


def test_vector_byte_identical(vector):
    """Python encode_frame produces byte-identical output to the golden vector.

    This works because Python preserves dict insertion order in msgpack.packb,
    and the generator uses the same encode_frame function.
    """
    name, bin_data, meta = vector

    # Decode to get the payload
    msg_type, req_id, payload = decode_frame(bin_data)

    # Re-encode
    reencoded = encode_frame(IPCMessageType(msg_type), req_id, payload)

    # Should be byte-identical for Python↔Python
    assert bin_data == reencoded, f"{name}: Python re-encode not byte-identical"


def test_all_vectors_have_valid_types():
    """Every vector file has a valid IPCMessageType."""
    if not FIXTURES_DIR.exists():
        pytest.skip("fixtures not found")

    count = 0
    for bin_file in FIXTURES_DIR.glob("*.bin"):
        data = bin_file.read_bytes()
        type_byte = data[4]
        try:
            IPCMessageType(type_byte)
        except ValueError:
            pytest.fail(f"{bin_file.name}: unknown type 0x{type_byte:02x}")
        count += 1

    assert count >= 20, f"expected at least 20 vectors, found {count}"


def test_frame_structure():
    """Validate the frame structure of a known vector."""
    bin_path = FIXTURES_DIR / "ping.bin"
    if not bin_path.exists():
        pytest.skip("ping.bin not found")

    data = bin_path.read_bytes()

    # Length field (4 bytes BE)
    length = struct.unpack(">I", data[:4])[0]
    assert length == len(data) - 4

    # Type byte
    assert data[4] == IPCMessageType.PING

    # Request ID (16 bytes)
    req_id = data[5:21]
    assert len(req_id) == 16
    assert req_id == FIXED_REQUEST_ID

    # Payload (msgpack empty dict = 0x80)
    payload_bytes = data[21:]
    payload = msgpack.unpackb(payload_bytes, raw=False)
    assert payload == {}
